services:
  - type: web
    name: telegram-autopost-bot
    runtime: docker  # <-- Это ключевой момент!
    repo: https://github.com/Dimaceo18/telegram-autopost-bot
    branch: main
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
